name: Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          if test 'wthfromtestsecrets' = ${{ secrets.HELLO }}; then echo 'HELLO'; else echo 'BROTHER'; fi
